{% set version = "0.8.4" %}

package:
  name: ypy-websocket
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/y/ypy-websocket/ypy_websocket-{{ version }}.tar.gz
  sha256: 43a001473f5c8abcf182f603049cf305cbc855ad8deaa9dfa0f3b5a7cea9d0ff

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling
    - pip
    - python >=3.7
  run:
    - aiofiles >=22.1.0,<23
    - aiosqlite >=0.17.0,<1
    - python >=3.7
    - y-py >=0.6.0,<0.7.0

test:
  source_files:
    - tests
  requires:
    - nodejs >=18,<19
    - pip
    - pytest-asyncio
    - pytest-cov
    - websockets >=10.0
  imports:
    - ypy_websocket
  commands:
    - pip check
    - cd tests && npm install
    - cd .. && pytest -vv --asyncio-mode=auto --cov-branch --cov=ypy_websocket --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=78

about:
  home: https://github.com/y-crdt/ypy-websocket
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WebSocket connector for Ypy

extra:
  recipe-maintainers:
    - davidbrochart
    - conda-forge/jupyter_server
