{% set version = "0.12.2" %}

package:
  name: ypy-websocket
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/y/ypy-websocket/ypy_websocket-{{ version }}.tar.gz
  sha256: 1d0f876e6a586248c54b52735798cc473e5800f8cd4acd050b5d5f20f2ef9bf6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatchling
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - aiosqlite >=0.18.0,<1
    - y-py >=0.6.0,<0.7.0
    - anyio >=3.6.2,<4
    - typing_extensions

test:
  source_files:
    - tests
  requires:
    - nodejs >=18,<19
    - pip
    - pytest-asyncio
    - pytest-cov
    - websockets >=10.0
    - uvicorn
  imports:
    - ypy_websocket
  commands:
    - pip check
    - cd tests && npm install
    - cd .. && pytest -vv --asyncio-mode=auto --cov-branch --cov=ypy_websocket --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=73

about:
  home: https://github.com/y-crdt/ypy-websocket
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WebSocket connector for Ypy
  doc_url: https://davidbrochart.github.io/ypy-websocket

extra:
  recipe-maintainers:
    - davidbrochart
    - conda-forge/jupyter_server
