{% set name = "ypy-websocket" %}
{% set version = "0.1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/y/ypy_websocket/ypy_websocket-{{ version }}.tar.gz
  sha256: f11b8b5adb37957bb3536704710882442aca798fad8fbe3182069d7e7f560f54

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - y-py >=0.5.0,<0.6.0
    - aiofiles >=0.8.0,<1
    - aiosqlite >=0.17.0,<1

test:
  imports:
    - ypy_websocket

about:
  home: https://github.com/y-crdt/ypy-websocket
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: WebSocket connector for Ypy
  dev_url: https://github.com/y-crdt/ypy-websocket

extra:
  recipe-maintainers:
    - davidbrochart
